---
title: Backspace
timezone: Europe/Amsterdam
description: 'Backspace is a startup studio driven by technology. Together we build
  complex technologies into commercial companies.

'
baseurl: 
twitter_username: backspacehq
github_username: backspacehq
facebook_username: backspacehq
dribbble_username: backspace
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
email: hello@backspace.studio
