---
title: Backspace
description: > # this means to ignore newlines until "baseurl:"
  Backspace is a startup studio driven by technology.
  Together we build complex technologies into commercial companies.
baseurl: ""
url: http://backspace.studio
twitter_username: backspacehq
github_username:  backspacehq
facebook_username:  Backspace-959766040737542
dribbble_username: backspace
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty
email: hello@backspace.studio
timezone: Europe/Amsterdam
collections:
  milestones:
    title: Milestones
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
