---
title: Backspace
url: http://backspace.studio
timezone: Europe/Amsterdam
collections:
  milestones:
    title: Milestones
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  Backspace is a startup studio driven by technology. Together we build complex technologies into commercial companies.
baseurl: ''
twitter_username: backspacehq
github_username: backspacehq
facebook_username: Backspace-959766040737542
dribbble_username: backspace
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
email: hello@backspace.studio

defaults:
  -
    scope:
      path: ""
      type: "milestones"
    values:
      visible_date: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Jons Janssens"
      author_image: "/img/content/people/jons-janssens.png"
      summary: ""
      category: ""
      cover_image: ""
