# Site settings
title: Backspace Studio
email: info@disrupted.vc
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://disrupted.github.io" # the base hostname & protocol for your site
twitter_username: disruptedvc
github_username:  disrupted
markdown: redcarpet
highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json"]
